Safely uninstall old weak-modules-migrated modules

diff --git a/kmod/scoutfs-kmod.spec.in b/kmod/scoutfs-kmod.spec.in
--- a/kmod/scoutfs-kmod.spec.in
+++ b/kmod/scoutfs-kmod.spec.in
@@ -104,3 +104,15 @@ depmod -a
 %clean
 rm -rf %{buildroot}
 
+%preun
+# stash our modules for postun cleanup
+SCOUTFS_RPM_NAME=$(rpm -q %{name} | grep "%{version}-%{release}")
+rpm -ql $SCOUTFS_RPM_NAME | grep '\.ko$' > /var/run/%{name}-modules || true
+rm /var/run/%{name}-modules || true
+
+%postun
+/sbin/ldconfig
+
+if [ -x /sbin/weak-modules ]; then
+    cat /var/run/%{name}-modules | /sbin/weak-modules --remove-modules --no-initramfs
+fi
